version: '3'

services:
  db:
    image: ramakrishna41/sqlite3:latest
    volumes:
      - ./database:/usr/src/app/database
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends-on:
      - db